In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
sample_matrix=np.array(list_of_lists)
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,5,10)

array([1])

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [ ]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.zeros((4,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [ ]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(3,3)

array([[0.33344428, 0.22195183, 0.92721072],
       [0.23694822, 0.89307056, 0.19855423],
       [0.34333674, 0.79322059, 0.54284078]])

In [ ]:
np.random.randn(3,3)

array([[ 0.49334889,  1.01322581,  1.55845396],
       [-0.28211099, -0.17175664,  0.27408475],
       [ 1.07434295, -0.07001615, -1.84579778]])

In [ ]:
np.random.randint(1,5)

3

In [ ]:
np.random.randint(1,99,3)

array([26,  3,  4])

In [ ]:
np.random.randint(1,99,50)

array([84, 59, 95, 63, 29, 47, 93, 54,  9, 19, 67, 68, 48, 77, 39, 14, 54,
       80, 63, 66, 37, 12, 14, 86, 28, 20, 60, 38, 13, 98,  5, 21, 75, 48,
       55, 59, 96, 31, 74, 17, 27, 88, 92, 16, 88, 34, 22, 88, 59, 96])

In [ ]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
rand_array=np.random.randint(0,100,20)

In [ ]:
rand_array

array([59, 22, 81, 33, 38, 29, 75,  4, 45, 59, 79, 83, 73, 12, 75,  1, 12,
       37, 32,  6])

In [ ]:
sample_array.reshape(4,3)

ValueError: ignored

In [ ]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
rand_array.min()

1

In [ ]:
rand_array.argmin()

15

In [ ]:
rand_array

array([59, 22, 81, 33, 38, 29, 75,  4, 45, 59, 79, 83, 73, 12, 75,  1, 12,
       37, 32,  6])

In [ ]:
sample_array.min()

0

In [ ]:
a=np.eye(3)

In [ ]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a.T


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.randint(3,9)

5

In [ ]:
np.random.randint(1,99,50)

array([23, 36, 14, 71,  6, 86, 34, 14, 69, 93, 54, 29, 50, 30, 11, 66, 63,
       83, 13, 54, 86, 32, 37, 76, 46, 62, 55, 54, 60, 17, 19, 31, 62, 21,
       20, 23, 98, 58, 53, 49, 20, 89, 73, 76, 41, 34, 11, 57, 48, 94])

In [ ]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
sample_array[3]

3

In [ ]:
sample_array[3:7]

array([3, 4, 5, 6])

In [ ]:
sample_array[1:4]=100
sample_array

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [ ]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
sample_array[1:7]

array([11, 12, 13, 14, 15, 16])

In [ ]:
subset_sample_array=sample_array[0:7]

In [ ]:
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [ ]:
subset_sample_array[1:4]=1000

In [ ]:
subset_sample_array


array([  10, 1000, 1000, 1000,   14,   15,   16])

In [ ]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [ ]:
sample_matrix[0:2,2]

array([ 1, 21])

In [ ]:
sample_matrix[0:3,3]

array([23, 33,  7])

In [ ]:
sample_matrix[0:3,2]

array([ 1, 21, 24])

In [ ]:
sample_matrix[0:3,1]

array([20, 23, 76])

In [ ]:
sample